language: java
jdk: openjdk8
sudo: required
cache:
  directories:
    - $HOME/.m2/repository
stages:
  - name: build
  - name: test
jobs:
  include:
    - stage: build
      name: Build
      install: echo Not performing default install step
      script: mvn clean package -Dmaven.test.skip=true
    - stage: test
      name: Test
      before_install:
        - chmod +x mvnw
      script: ./mvnw test
